### ISSUE TITLE
Outline scenarios with examples are not working as expected

### ISSUE THREAD

**Issue by oliverde8** [cucumber/monaco#60]
Hello, first of all thank you for this awsome project 💖

### 👓 What did you see?

I am testing it with outline scenarios with examples. Undefined steps are not showing as undefined steps. 

### ✅ What did you expect to see?

I expected my invalid step to be reported as problem

### 📦 Which tool/library version are you using?

Reproduced on the Live Demo to remove variables. 

### 🔬 How could we reproduce it?

1. Visit https://cucumber.github.io/monaco/
2. Use the feature file below,

```gherkin
@foo
Feature: Hello
  Scenario Outline: Hi
    Given I have <qty> cukes in my belly
    And this is an undefined step

  Examples:
    | day            | answer |
    | Friday         | TGIF   |
    | Sunday         | Nope   |
    | anything else! | Nope   |
```

![image](https://github.com/cucumber/monaco/assets/3658513/2ec854cf-c77d-4abf-b8db-a940e2c4f86d)

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
Curious issue @oliverde8! The root cause lies within the Cucumber Language Service: it disables diagnostics for undefined steps if the test is a scenario outline (has an examples table). My reasoning is that this is due to the challenges in ensuring clear and reliable behaviour with respect to examples table lookup to consider whether the values match the step definition. This is in comparison to steps without parameters, where we can pass the step text to a validation function in its raw format.

I have captured an issue detailing proposing this as a feature request (cucumber/language-service/#149). I would greatly appreciate if you could take a look and provide any feedback.

**Comment by kieran-ryan** [comment]
@oliverde8, issue resolved - thanks for raising! Welcome further requests and if you observe any edge cases.

![image](https://github.com/cucumber/monaco/assets/5904340/876b66f5-906b-454b-a0b3-58589f06f394)
